# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BeltReviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_list', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='BeltReviewer.Authors')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_book', to='BeltReviewer.Books')),
            ],
        ),
        migrations.RenameField(
            model_name='users',
            old_name='first_name',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='last_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='reviews',
            name='user_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_rating', to='BeltReviewer.Users'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='user_reviews',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_reviews', to='BeltReviewer.Users'),
        ),
        migrations.AddField(
            model_name='books',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_books', to='BeltReviewer.Users'),
        ),
        migrations.AddField(
            model_name='books',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_books', to='BeltReviewer.Users'),
        ),
    ]
