# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeltReviewer', '0002_auto_20170925_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='author_list',
            new_name='author_name',
        ),
    ]
